/* ==========================================================================
   PHASE 6 SPECIES SYSTEMS — physical evolution state machine, explicit shiny
   material profiles, and reusable species ability contracts.
   ========================================================================== */
(function (global) {
  'use strict';

  const EVOLUTION_FORMS = Object.freeze([
    'vaporeon', 'jolteon', 'flareon', 'espeon',
    'umbreon', 'leafeon', 'glaceon', 'sylveon'
  ]);

  const ABILITIES = Object.freeze({
    vaporeon: { id: 'water-shape', targetType: 'water', label: 'Shape Water', color: 0x58c9ff, mutation: 'flooded' },
    jolteon:  { id: 'relay-charge', targetType: 'power', label: 'Charge Relay', color: 0xffed55, mutation: 'charged' },
    flareon:  { id: 'hearth-heat', targetType: 'heat', label: 'Kindle Heat', color: 0xff713d, mutation: 'heated' },
    espeon:   { id: 'psychic-shift', targetType: 'telekinesis', label: 'Shift Matter', color: 0xd48cff, mutation: 'aligned' },
    umbreon:  { id: 'moon-veil', targetType: 'shadow', label: 'Cast Moon Veil', color: 0x5472ff, mutation: 'veiled' },
    leafeon:  { id: 'verdant-growth', targetType: 'growth', label: 'Accelerate Growth', color: 0x78ce63, mutation: 'grown' },
    glaceon:  { id: 'crystal-freeze', targetType: 'freeze', label: 'Crystal Freeze', color: 0x9aeaff, mutation: 'frozen' },
    sylveon:  { id: 'ribbon-bind', targetType: 'bind', label: 'Ribbon Bind', color: 0xff9bc7, mutation: 'bound' }
  });

  // Explicit profiles replace the old whole-model one-color tint. The keys below
  // match the checked-in rig manifest. Unknown materials are preserved rather than
  // guessed. Umbreon uses named pattern rules because its deep material inventory
  // is still connector-partial and is regenerated by the existing Phase-0 tool.
  const SHINY_PROFILES = Object.freeze({
    eevee: {
      exact: {
        'Material__12.001': { color: 0xe7e3da },
        'Material__13.001': { color: 0xf7f4ed },
        'Material__14': { color: 0xa89f95 }
      }
    },
    vaporeon: {
      exact: {
        'Material_10': { color: 0xdf78d7 },
        'Material_11': { color: 0xf4d8ef },
        'Material_12': { color: 0x8a5799 }
      }
    },
    jolteon: {
      exact: {
        'Material__10.001': { color: 0xb9d64c },
        'Material__11.001': { color: 0xf0f0cf }
      }
    },
    flareon: {
      exact: {
        'Material__10': { color: 0xf1a343 },
        'Material__11': { color: 0xffdf91 },
        'Material__12': { color: 0x8b5a3a },
        'Material__13': { color: 0xffefbe }
      }
    },
    espeon: {
      exact: {
        'Material__105': { color: 0x73d88e },
        'Material__106': { color: 0xb9f0c3 },
        'Material__107': { color: 0xff3355, emissive: 0xff2448, emissiveIntensity: 0.7 }
      }
    },
    umbreon: {
      rules: [
        { pattern: 'ring', color: 0x38d8ff, emissive: 0x00a2ff, emissiveIntensity: 0.9 },
        { pattern: 'body_b', color: 0x38d8ff, emissive: 0x00a2ff, emissiveIntensity: 0.65 },
        { pattern: 'body_a', color: 0x172532 }
      ]
    },
    leafeon: {
      exact: {
        'Material__11.004': { color: 0xd7c795 },
        'Material__12.004': { color: 0x83bd62 },
        'Material__13.003': { color: 0xb06e42 }
      }
    },
    glaceon: {
      exact: {
        'Material__24': { color: 0x9fe6f0 },
        'Material__25': { color: 0xe1f6f8 },
        'Material__26': { color: 0x477b9b }
      }
    },
    sylveon: {
      exact: {
        'Material__10.004': { color: 0xf8f1e9 },
        'Material__11.005': { color: 0x74d4ef },
        'Material__12.005': { color: 0xf0b1cf },
        'Material__13.004': { color: 0x5577a8 }
      }
    }
  });

  function profileEntry(species, materialName) {
    const profile = SHINY_PROFILES[species];
    if (!profile) return null;
    if (profile.exact && profile.exact[materialName]) return profile.exact[materialName];
    if (profile.rules) {
      const lower = String(materialName || '').toLowerCase();
      return profile.rules.find(rule => lower.includes(rule.pattern)) || null;
    }
    return null;
  }

  function restoreRecord(record) {
    if (!record || !record.mat) return;
    if (record.mat.color && record.color) record.mat.color.copy(record.color);
    if (record.mat.emissive && record.emissive) record.mat.emissive.copy(record.emissive);
    if ('emissiveIntensity' in record.mat) record.mat.emissiveIntensity = Number(record.emissiveIntensity) || 0;
  }

  function applyShinyProfile(species, materialRecords, shiny) {
    let matched = 0;
    (materialRecords || []).forEach(record => {
      restoreRecord(record);
      if (!shiny) return;
      const rule = profileEntry(species, record.name || (record.mat && record.mat.name));
      if (!rule || !record.mat) return;
      matched++;
      if (rule.color != null && record.mat.color) record.mat.color.setHex(rule.color);
      if (rule.emissive != null && record.mat.emissive) record.mat.emissive.setHex(rule.emissive);
      if (rule.emissiveIntensity != null && 'emissiveIntensity' in record.mat) record.mat.emissiveIntensity = rule.emissiveIntensity;
    });
    return matched;
  }

  class AbilitySystem {
    constructor(options) {
      options = options || {};
      this.worldState = options.worldState || null;
      this.roomManager = options.roomManager || null;
    }

    setRoomManager(roomManager) { this.roomManager = roomManager || null; }

    getDefinition(species) { return ABILITIES[species] || null; }

    canUseAbility(species, target) {
      const def = this.getDefinition(species);
      const meta = target && target.userData ? target.userData.abilityTarget : null;
      return !!(def && meta && meta.targetType === def.targetType);
    }

    performAbility(species, target) {
      const def = this.getDefinition(species);
      const meta = target && target.userData ? target.userData.abilityTarget : null;
      if (!def) return { ok: false, reason: 'species-has-no-ability' };
      if (!meta) return { ok: false, reason: 'no-ability-target' };
      if (meta.targetType !== def.targetType) {
        return { ok: false, reason: 'incompatible-target', required: def.targetType, targetType: meta.targetType };
      }

      const roomId = meta.roomId || (this.roomManager && this.roomManager.current ? this.roomManager.current.id : null);
      const mutation = {
        roomId,
        targetId: meta.id,
        species,
        abilityId: def.id,
        targetType: def.targetType,
        mutation: def.mutation
      };

      if (this.worldState && roomId) this.worldState.recordAbilityMutation(roomId, meta.id, mutation);
      if (this.roomManager && this.roomManager.applyAbilityMutation) this.roomManager.applyAbilityMutation(mutation);
      return { ok: true, definition: def, mutation };
    }
  }

  class EvolutionController {
    constructor(options) {
      options = options || {};
      this.actor = options.actor || null;
      this.getCurrentSpecies = options.getCurrentSpecies || (() => 'eevee');
      this.isSpeciesReady = options.isSpeciesReady || (() => true);
      this.reducedMotion = options.reducedMotion || (() => false);
      this.onStage = options.onStage || function () {};
      this.onSwap = options.onSwap || function () {};
      this.onComplete = options.onComplete || function () {};
      this.reset();
    }

    reset() {
      this.state = 'idle';
      this.targetSpecies = null;
      this.stoneObject = null;
      this.approachPoint = null;
      this.elapsed = 0;
      this.swapDone = false;
      this.commitRequested = false;
    }

    isActive() { return this.state !== 'idle'; }

    _stoneWorldPosition(stoneObject) {
      if (!stoneObject) return null;
      if (stoneObject.getWorldPosition && global.THREE && global.THREE.Vector3) {
        return stoneObject.getWorldPosition(new global.THREE.Vector3());
      }
      return stoneObject.position && stoneObject.position.clone ? stoneObject.position.clone() : null;
    }

    request(targetSpecies, stoneObject) {
      if (!EVOLUTION_FORMS.includes(targetSpecies)) return { ok: false, reason: 'invalid-target' };
      if (this.getCurrentSpecies() !== 'eevee') return { ok: false, reason: 'requires-eevee' };
      if (!this.isSpeciesReady(targetSpecies)) return { ok: false, reason: 'model-not-ready' };

      if (this.isActive()) {
        if (targetSpecies !== this.targetSpecies) return { ok: false, reason: 'evolution-busy' };
        this.commitRequested = true;
        if (this.state === 'ready') this._beginCharge();
        return { ok: true, state: this.state, committed: true };
      }

      const stonePos = this._stoneWorldPosition(stoneObject);
      if (!stonePos || !this.actor || !this.actor.root) return { ok: false, reason: 'missing-actor-or-stone' };

      const approach = stonePos.clone();
      approach.y = 0;
      const away = this.actor.root.position.clone().sub(stonePos);
      away.y = 0;
      if (away.lengthSq && away.lengthSq() > 0.0001) away.normalize().multiplyScalar(0.72);
      else if (away.set) away.set(0, 0, 0.72);
      approach.add(away);

      this.state = 'approach';
      this.targetSpecies = targetSpecies;
      this.stoneObject = stoneObject;
      this.approachPoint = approach;
      this.elapsed = 0;
      this.actor.clearBehaviorState && this.actor.clearBehaviorState();
      this.actor.moveTo(approach, { source: 'evolution' });
      this.actor.lookAtWorld && this.actor.lookAtWorld(stonePos, 3.0);
      this.onStage('approach', this.getDebugState());
      return { ok: true, state: this.state, committed: false };
    }

    _beginCharge() {
      if (this.state !== 'ready' && this.state !== 'approach') return false;
      this.state = 'charge';
      this.elapsed = 0;
      this.actor.stop && this.actor.stop();
      this.actor.hold && this.actor.hold(this.reducedMotion() ? 0.35 : 1.2);
      this.onStage('charge', this.getDebugState());
      return true;
    }

    update(dt) {
      if (!this.isActive()) return;
      dt = Math.max(0, Math.min(Number(dt) || 0, 0.1));
      this.elapsed += dt;

      if (this.state === 'approach') {
        const p = this.actor && this.actor.root ? this.actor.root.position : null;
        if (!p || !this.approachPoint) return;
        const dx = p.x - this.approachPoint.x;
        const dz = p.z - this.approachPoint.z;
        const arrived = Math.sqrt(dx * dx + dz * dz) < 0.18 ||
          (this.actor.state === 'idle' && !this.actor.target) ||
          this.elapsed > 5;
        if (!arrived) return;
        this.state = 'ready';
        this.elapsed = 0;
        this.actor.hold && this.actor.hold(0.5);
        this.onStage('ready', this.getDebugState());
        if (this.commitRequested) this._beginCharge();
        return;
      }

      if (this.state === 'charge') {
        const swapAt = this.reducedMotion() ? 0.12 : 0.42;
        if (!this.swapDone && this.elapsed >= swapAt) {
          this.swapDone = true;
          this.onSwap(this.targetSpecies, this.getDebugState());
          this.state = 'reveal';
          this.elapsed = 0;
          this.onStage('reveal', this.getDebugState());
        }
        return;
      }

      if (this.state === 'reveal') {
        const finishAt = this.reducedMotion() ? 0.12 : 0.55;
        if (this.elapsed < finishAt) return;
        const completed = this.targetSpecies;
        this.onStage('complete', this.getDebugState());
        this.onComplete(completed);
        this.reset();
      }
    }

    cancel(reason) {
      if (!this.isActive()) return false;
      const snapshot = this.getDebugState();
      this.onStage('cancel', Object.assign(snapshot, { reason: reason || 'cancelled' }));
      this.reset();
      return true;
    }

    getDebugState() {
      return {
        state: this.state,
        targetSpecies: this.targetSpecies,
        commitRequested: this.commitRequested,
        swapDone: this.swapDone,
        active: this.isActive()
      };
    }
  }

  global.EeveePhase6System = {
    EVOLUTION_FORMS,
    ABILITIES,
    SHINY_PROFILES,
    profileEntry,
    applyShinyProfile,
    AbilitySystem,
    EvolutionController
  };
})(window);
